<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'nizsheanez\\assetConverter\\' => array($vendorDir . '/nizsheanez/yii2-asset-converter'),
    'Prophecy\\' => array($vendorDir . '/phpspec/prophecy/src'),
    'PayPal\\Service' => array($vendorDir . '/paypal/merchant-sdk-php/lib'),
    'PayPal\\PayPalAPI' => array($vendorDir . '/paypal/merchant-sdk-php/lib'),
    'PayPal\\EnhancedDataTypes' => array($vendorDir . '/paypal/merchant-sdk-php/lib'),
    'PayPal\\EBLBaseComponents' => array($vendorDir . '/paypal/merchant-sdk-php/lib'),
    'PayPal\\CoreComponentTypes' => array($vendorDir . '/paypal/merchant-sdk-php/lib'),
    'PayPal' => array($vendorDir . '/paypal/sdk-core-php/lib'),
    'Less' => array($vendorDir . '/oyejorge/less.php/lib'),
    'HTMLPurifier' => array($vendorDir . '/ezyang/htmlpurifier/library'),
    'Diff' => array($vendorDir . '/phpspec/php-diff/lib'),
    'Behat\\Gherkin' => array($vendorDir . '/behat/gherkin/src'),
);
